{% set maturin_version = ">=1.2.3,<2" %}
{% set version = "0.3.4" %}

package:
  name: pycrdt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycrdt/pycrdt-{{ version }}.tar.gz
  sha256: 02503edda929196046c12cd64c58e437f3674f2eaa46072df8220e56980c2d4c

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin {{ maturin_version }}          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin {{ maturin_version }}
    - pip
    - python
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pycrdt

about:
  home: https://github.com/davidbrochart/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  dev_url: https://github.com/davidbrochart/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
