{% set name = "pycrdt" %}
{% set version = "0.12.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 506d4bc00d7d566de4018dca52998ab7cf97c787363bc59440d3a3bb3336d1a0

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  skip: true  # [py<310]

requirements:
  build:
    - python
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin >=1.8.2,<2
  host:
    - maturin >=1.8.2,<2
    - pip
    - python
  run:
    - python
    - anyio >=4.4.0,<5.0.0
    - typing_extensions >=4.14.0  # [py<311]
    - exceptiongroup  # [py<311]

# >       assert len(changes) == 5
# E       AssertionError: assert 6 == 5
{% set tests_to_skip = "test_awareness_periodic_updates" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - pycrdt
    - pycrdt._awareness
    - pycrdt._doc
    - pycrdt._text
    - pycrdt._array
    - pycrdt._map
    - pycrdt._transaction
    - pycrdt._undo
    - pycrdt._update
    - pycrdt._sync
  commands:
    - pip check
    - pytest -v tests  # [not win]
    - pytest -v -k "not ({{ tests_to_skip }})" tests  # [win]
  requires:
    - pip
    - pytest >=8.3.5,<10
    - trio >=0.25.1,<0.34
    - pydantic >=2.5.2,<3
    - exceptiongroup  # [py<311]

about:
  home: https://github.com/y-crdt/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  description: Pycrdt is a Python CRDT library that provides bindings for Yrs, the Rust port of the Yjs framework.
  dev_url: https://github.com/y-crdt/pycrdt
  doc_url: https://jupyter-server.github.io/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
