{% set name = "pycrdt" %}
{% set version = "0.14.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 508d1d1a573faec11236cdb69f793682591845b0b0184fbfe9c49147e9625044

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  skip: true  # [py<310]

requirements:
  build:
    - python
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin >=1.8.2,<2
  host:
    - maturin >=1.8.2,<2
    - pip
    - python
  run:
    - python
    - anyio >=4.4.0,<5.0.0
    - typing_extensions >=4.15.0,<5.0.0  # [py<311]
    - exceptiongroup  # [py<311]

# >       assert len(changes) == 5
# E       AssertionError: assert 6 == 5
{% set tests_to_skip = "test_awareness_periodic_updates" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - pycrdt
    - pycrdt._awareness
    - pycrdt._doc
    - pycrdt._text
    - pycrdt._array
    - pycrdt._map
    - pycrdt._transaction
    - pycrdt._undo
    - pycrdt._update
    - pycrdt._sync
  commands:
    - pip check
    - pytest -v tests  # [not win]
    - pytest -v -k "not ({{ tests_to_skip }})" tests  # [win]
  requires:
    - pip
    - pytest >=8.3.5,<10
    - trio >=0.25.1,<0.35
    - pydantic >=2.5.2,<3
    - anyio

about:
  home: https://github.com/y-crdt/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  description: Pycrdt is a Python CRDT library that provides bindings for Yrs, the Rust port of the Yjs framework.
  dev_url: https://github.com/y-crdt/pycrdt
  doc_url: https://y-crdt.github.io/pycrdt/

extra:
  recipe-maintainers:
    - davidbrochart
