{% set maturin_version = ">=1.4.0,<2" %}
{% set version = "0.9.11" %}

package:
  name: pycrdt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycrdt/pycrdt-{{ version }}.tar.gz
  sha256: 544cf5ff97615d8b06ae38b11d7788e7612fc341c997a170d57695beead4249b

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python
    - anyio >=4.4.0,<5.0.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pycrdt
    - pycrdt._doc
    - pycrdt._text
    - pycrdt._array
    - pycrdt._map
    - pycrdt._transaction
    - pycrdt._undo
    - pycrdt._sync

about:
  home: https://github.com/jupyter-server/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  dev_url: https://github.com/jupyter-server/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
