{% set maturin_version = ">=1.4.0,<2" %}
{% set version = "0.8.4" %}

package:
  name: pycrdt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycrdt/pycrdt-{{ version }}.tar.gz
  sha256: 7b246cb47c242a1a32dfb75bb1f31f398ed8acd8351cd581615e378d2b6385dd

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin {{ maturin_version }}          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin {{ maturin_version }}
    - pip
    - python
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pycrdt
    - pycrdt.doc
    - pycrdt.text
    - pycrdt.array
    - pycrdt.map
    - pycrdt.transaction

about:
  home: https://github.com/jupyter-server/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  dev_url: https://github.com/jupyter-server/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
