{% set version = "0.8.2" %}

package:
  name: pycrdt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycrdt/pycrdt-{{ version }}.tar.gz
  sha256: 50817c55c8c4dd0f6df0f67f34c34bedc3fba440019b1e8d87b0e0579b6d79d8

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pycrdt
    - pycrdt.doc
    - pycrdt.text
    - pycrdt.array
    - pycrdt.map
    - pycrdt.transaction

about:
  home: https://github.com/jupyter-server/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  dev_url: https://github.com/jupyter-server/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
