{% set name = "pycrdt" %}
{% set version = "0.12.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbf1d4785a25f614b057a1d7c66539bcd6ee4cd5aaa00c93f1f2ac5d0ae1f9c3

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  skip: True  # [py<39]

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # upstream repo needs - maturin >=1.8.2,<2 only 1.7.8 in main channel is available.
    - maturin >=1.7.8,<2
  host:
    - maturin >=1.7.8,<2
    - pip
    - python
  run:
    - python
    - anyio >=4.4.0,<5.0.0
    - importlib_metadata >=3.6

test:
  source_files:
    - tests
  imports:
    - pycrdt
    - pycrdt._awareness
    - pycrdt._doc
    - pycrdt._text
    - pycrdt._array
    - pycrdt._map
    - pycrdt._transaction
    - pycrdt._undo
    - pycrdt._update
    - pycrdt._sync
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest >=7.4.2,<8
    - anyio
    - trio >=0.25.1,<0.30
    - pydantic >=2.5.2,<3

about:
  home: https://github.com/jupyter-server/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  description: Pycrdt is a Python CRDT library that provides bindings for Yrs, the Rust port of the Yjs framework.
  dev_url: https://github.com/jupyter-server/pycrdt
  doc_url: https://jupyter-server.github.io/pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
